{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "L13V8vG_aAW9"
   },
   "outputs": [],
   "source": [
    "PATH_ORG = \"./CEDAR/signatures/full_org\"\n",
    "PATH_FORG = \"./CEDAR/signatures/full_forg\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "RkSYqGtiVJzY"
   },
   "outputs": [],
   "source": [
    "import os\n",
    "from natsort import natsorted, ns\n",
    "\n",
    "def get_image_list():\n",
    "  org_signs = os.listdir(\"./CEDAR/signatures/full_org\")\n",
    "  forg_signs = os.listdir(\"./CEDAR/signatures/full_forg\")\n",
    "  org_signs = [s for s in org_signs if s.endswith(\".png\")]\n",
    "  forg_signs = [s for s in forg_signs if s.endswith(\".png\")]\n",
    "  org_signs = natsorted(org_signs, alg=ns.IGNORECASE)\n",
    "  forg_signs = natsorted(forg_signs, alg=ns.IGNORECASE)\n",
    "  return org_signs, forg_signs\n",
    "\n",
    "# data cleaning\n",
    "def check_lists(org_signs,forg_signs):\n",
    "  flag = False\n",
    "  for i in range(len(org_signs)):\n",
    "    org_ext = org_signs[i][8:]\n",
    "    forg_ext = forg_signs[i][9:]\n",
    "    if org_ext != forg_ext:\n",
    "      flag = True\n",
    "      #print(i,org_ext,forg_ext)\n",
    "  '''if(flag):\n",
    "    #print(\"Mismatches found\")\n",
    "  else:\n",
    "    #print(\"No mismatch found\")\n",
    "'''\n",
    "def refine_lists(org_signs,forg_signs):\n",
    "  refined_org_signs = []\n",
    "  for i in range(len(org_signs)):\n",
    "    if \"_41_\" in org_signs[i]:\n",
    "      continue\n",
    "    refined_org_signs.append(org_signs[i])\n",
    "  \n",
    "  refined_forg_signs = []\n",
    "  for i in range(len(forg_signs)):\n",
    "    if \"_41_\" in forg_signs[i]:\n",
    "      continue\n",
    "    refined_forg_signs.append(forg_signs[i])\n",
    "  return refined_org_signs, refined_forg_signs\n",
    "\n",
    "def get_clean_lists():\n",
    "  org_signs, forg_signs = get_image_list()\n",
    "  check_lists(org_signs,forg_signs)\n",
    "  org_signs, forg_signs = refine_lists(org_signs,forg_signs)\n",
    "  #print(len(org_signs),len(forg_signs))\n",
    "  check_lists(org_signs,forg_signs)\n",
    "  return org_signs, forg_signs\n",
    "\n",
    "import random\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "def get_dataframe(org_signs,forg_signs):\n",
    "  no_of_ppl = len(org_signs)//24\n",
    "\n",
    "  raw_data = {\"image_1\":[], \"image_2\":[], \"label\":[]}\n",
    "  for i in range(no_of_ppl):\n",
    "    i1_batch_1 = []\n",
    "    i1_batch_2 = []\n",
    "    i2_batch = []\n",
    "\n",
    "    start = i*24\n",
    "    end = (i+1)*24\n",
    "\n",
    "    for j in range(start,end): \n",
    "      i1_batch_1.append(os.path.join(PATH_ORG,org_signs[j]))\n",
    "      i1_batch_2.append(os.path.join(PATH_ORG,org_signs[j]))\n",
    "      raw_data[\"label\"].append(1)#0\n",
    "\n",
    "    temp_rot = (i1_batch_1[-12:]+i1_batch_1[:-12])\n",
    "    i1_batch_1.extend(i1_batch_2)\n",
    "\n",
    "    for elem in temp_rot:\n",
    "      i2_batch.append(elem)\n",
    "\n",
    "    for j in range(start,end): \n",
    "      i2_batch.append(os.path.join(PATH_FORG,forg_signs[j]))\n",
    "      raw_data[\"label\"].append(0)#1\n",
    "\n",
    "    raw_data[\"image_1\"].extend(i1_batch_1)\n",
    "    raw_data[\"image_2\"].extend(i2_batch)\n",
    "  df = pd.DataFrame(raw_data, columns = [\"image_1\",\"image_2\",\"label\"])\n",
    "  df=df.reindex(np.random.permutation(df.index))\n",
    "  return df\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "def get_dataset(subset=None):\n",
    "  org_signs,forg_signs = get_clean_lists()\n",
    "  df = get_dataframe(org_signs,forg_signs)\n",
    "  #print(df.shape)\n",
    "  train_set, val_set = train_test_split(df,test_size=0.3,random_state=0)\n",
    "  if(subset.lower()==\"train\"):\n",
    "    dataset = train_set\n",
    "  else:\n",
    "    dataset = val_set\n",
    "  return dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "colab_type": "code",
    "id": "tBLZsJmOaai3",
    "outputId": "74f7fccf-80f9-4203-d430-50c1dcea567c"
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import keras\n",
    "from PIL import Image\n",
    "import cv2\n",
    "\n",
    "class DataGenerator(keras.utils.Sequence):\n",
    "    \n",
    "    def __init__(self, df, batch_size=32, dim=(155,220), n_channels=3, shuffle=True):\n",
    "        self.dim = dim\n",
    "        self.batch_size = batch_size\n",
    "        self.df = df\n",
    "        self.labels = df[\"label\"]\n",
    "        self.n_channels = n_channels\n",
    "        self.shuffle = shuffle\n",
    "        self.on_epoch_end()\n",
    "\n",
    "    def __len__(self):\n",
    "        return int(np.floor(self.df.shape[0] / self.batch_size))\n",
    "\n",
    "    def __getitem__(self, index):\n",
    "        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]\n",
    "        rows = [self.df.iloc[k] for k in indexes]\n",
    "        X, y = self.__data_generation(rows)\n",
    "        return X, y\n",
    "\n",
    "    def on_epoch_end(self):\n",
    "        self.indexes = np.arange(self.df.shape[0])\n",
    "        if self.shuffle == True:\n",
    "            np.random.shuffle(self.indexes)\n",
    "\n",
    "    def __data_generation(self, rows):\n",
    "        x_1 = np.empty((self.batch_size, *self.dim, self.n_channels))\n",
    "        x_2 = np.empty((self.batch_size, *self.dim, self.n_channels))\n",
    "        y = np.empty((self.batch_size), dtype=int)\n",
    "        \n",
    "        for i in range(len(rows)):\n",
    "            image_1 = cv2.imread(rows[i][\"image_1\"])\n",
    "            image_1 = cv2.resize(image_1,(220,155))\n",
    "            image_1 = cv2.bitwise_not(image_1)\n",
    "            image_1=np.array(image_1)\n",
    "            image_2 = cv2.imread(rows[i][\"image_2\"])\n",
    "            image_2 = cv2.resize(image_2,(220,155))\n",
    "            image_2 = cv2.bitwise_not(image_2)\n",
    "            image_2=np.array(image_2)\n",
    "            '''mean_center_1 = image_1 - np.mean(image_1, axis = None)\n",
    "            mean_center_2 = image_2 - np.mean(image_2, axis = None)\n",
    "            \n",
    "            std_1 = np.std(image_1)\n",
    "            std_2 = np.std(image_2)\n",
    "            if(std_1 == 0 or std_1 == np.nan):\n",
    "                std_1 = 1\n",
    "            if(std_2 == 0 or std_2 == np.nan):\n",
    "                std_2 = 1\n",
    "            standardized_img_1 = image_1/std_1\n",
    "            standardized_img_2 = image_2/std_2\n",
    "            '''\n",
    "            x_1[i,] = image_1/255\n",
    "            x_2[i,] = image_2/255\n",
    "            y[i] = rows[i][\"label\"]\n",
    "\n",
    "\n",
    "        return [x_1, x_2], y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "1oCcDpZhxAfq"
   },
   "outputs": [],
   "source": [
    "from keras import models\n",
    "from keras.layers import Conv2D, MaxPooling2D, Dense, Activation, BatchNormalization, Input, Dropout, Flatten\n",
    "from keras.models import Model\n",
    "\n",
    "def get_base_net():\n",
    "  input = Input(shape=(155,220,3))\n",
    "  \n",
    "  conv_1 = Conv2D(filters=96, kernel_size=(11,11))(input)\n",
    "  batch_norm_1 = BatchNormalization()(conv_1)\n",
    "  activation_1 = Activation('relu')(batch_norm_1)\n",
    "  max_pool_1 = MaxPooling2D(pool_size=(3,3))(activation_1)\n",
    "  \n",
    "  conv_2 = Conv2D(filters=256, kernel_size=(5,5))(max_pool_1)\n",
    "  batch_norm_2 = BatchNormalization()(conv_2)\n",
    "  activation_2 = Activation('relu')(batch_norm_2)\n",
    "  max_pool_2 = MaxPooling2D(pool_size=(3,3))(activation_1)\n",
    "  \n",
    "  dropout_1 = Dropout(rate=0.3)(max_pool_2)\n",
    "  \n",
    "  conv_3_a = Conv2D(filters=384, kernel_size=(3,3))(dropout_1)\n",
    "  activation_3_a = Activation('relu')(conv_3_a)\n",
    "  conv_3_b = Conv2D(filters=256, kernel_size=(3,3))(activation_3_a)\n",
    "  activation_3_b = Activation('relu')(conv_3_b)\n",
    "  max_pool_3 = MaxPooling2D(pool_size=(3,3))(activation_3_b)\n",
    "  \n",
    "  dropout_2 = Dropout(rate=0.3)(max_pool_3)\n",
    "  \n",
    "  flat_1 = Flatten()(dropout_2)\n",
    "  fc_1 = Dense(units=1024,activation='relu')(flat_1)\n",
    "  dropout_3 = Dropout(rate=0.5)(fc_1)\n",
    "  fc_2 = Dense(units=128,activation='relu')(dropout_3)\n",
    "  return Model(input,fc_2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "akHC-9pD_QJb"
   },
   "outputs": [],
   "source": [
    "from keras import backend as K\n",
    "\n",
    "def euclidean_distance(vects):\n",
    "    x, y = vects\n",
    "    sum_square = K.sum(K.square(x - y), axis=1, keepdims=True)\n",
    "    return K.sqrt(K.maximum(sum_square, K.epsilon()))\n",
    "\n",
    "\n",
    "def eucl_dist_output_shape(shapes):\n",
    "    shape1, shape2 = shapes\n",
    "    return (shape1[0], 1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "r-WsFbXsBKqY"
   },
   "outputs": [],
   "source": [
    "def contrastive_loss(y_true, y_pred):\n",
    "    margin = 1\n",
    "    #print(\"y_pred\",y_pred)\n",
    "    sqaure_pred = K.square(y_pred)\n",
    "    margin_square = K.square(K.maximum(margin - y_pred, 0))\n",
    "    return K.mean(y_true * sqaure_pred + (1 - y_true)* margin_square)\n",
    "  \n",
    "def accuracy(y_true, y_pred):\n",
    "    return K.mean(K.equal(y_true, K.cast(y_pred < 0.5, y_true.dtype)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "vnmcc7oJ8d3c"
   },
   "outputs": [],
   "source": [
    "from keras.layers import Lambda\n",
    "\n",
    "input_a = Input(shape=(155,220,3))\n",
    "input_b = Input(shape=(155,220,3))\n",
    "\n",
    "base_net = get_base_net()\n",
    "processed_a = base_net(input_a)\n",
    "processed_b = base_net(input_b)\n",
    "\n",
    "distance = Lambda(euclidean_distance,output_shape=eucl_dist_output_shape)([processed_a, processed_b])\n",
    "model = Model([input_a, input_b], distance)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "nnuE0iNfC-Ae"
   },
   "outputs": [],
   "source": [
    "from keras import optimizers\n",
    "optimizer = optimizers.RMSprop()\n",
    "model.compile(loss=contrastive_loss, optimizer=optimizer, metrics=[accuracy])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "AbZWL9zuuRxU",
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/30\n",
      "114/114 [==============================] - 64s 559ms/step - loss: 31.7018 - accuracy: 0.6870 - val_loss: 0.4348 - val_accuracy: 0.4834\n",
      "\n",
      "Epoch 00001: val_accuracy improved from -inf to 0.48342, saving model to ./best_weights_for_Network.hdf5\n",
      "Epoch 2/30\n",
      "114/114 [==============================] - 57s 501ms/step - loss: 0.9282 - accuracy: 0.5636 - val_loss: 0.2963 - val_accuracy: 0.4847\n",
      "\n",
      "Epoch 00002: val_accuracy improved from 0.48342 to 0.48469, saving model to ./best_weights_for_Network.hdf5\n",
      "Epoch 3/30\n",
      "114/114 [==============================] - 57s 502ms/step - loss: 0.6428 - accuracy: 0.5285 - val_loss: 0.3599 - val_accuracy: 0.4974\n",
      "\n",
      "Epoch 00003: val_accuracy improved from 0.48469 to 0.49745, saving model to ./best_weights_for_Network.hdf5\n",
      "Epoch 4/30\n",
      "114/114 [==============================] - 57s 502ms/step - loss: 0.4959 - accuracy: 0.5663 - val_loss: 0.1788 - val_accuracy: 0.7079\n",
      "\n",
      "Epoch 00004: val_accuracy improved from 0.49745 to 0.70791, saving model to ./best_weights_for_Network.hdf5\n",
      "Epoch 5/30\n",
      "114/114 [==============================] - 57s 502ms/step - loss: 0.6940 - accuracy: 0.6968 - val_loss: 0.6871 - val_accuracy: 0.4783\n",
      "\n",
      "Epoch 00005: val_accuracy did not improve from 0.70791\n",
      "Epoch 6/30\n",
      "114/114 [==============================] - 57s 502ms/step - loss: 0.3977 - accuracy: 0.6891 - val_loss: 0.0481 - val_accuracy: 0.9898\n",
      "\n",
      "Epoch 00006: val_accuracy improved from 0.70791 to 0.98980, saving model to ./best_weights_for_Network.hdf5\n",
      "Epoch 7/30\n",
      "114/114 [==============================] - 60s 524ms/step - loss: 0.6233 - accuracy: 0.7144 - val_loss: 0.1536 - val_accuracy: 0.8559\n",
      "\n",
      "Epoch 00007: val_accuracy did not improve from 0.98980\n",
      "Epoch 8/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.5811 - accuracy: 0.6776 - val_loss: 0.1725 - val_accuracy: 0.7997\n",
      "\n",
      "Epoch 00008: val_accuracy did not improve from 0.98980\n",
      "Epoch 9/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.5890 - accuracy: 0.7412 - val_loss: 0.0172 - val_accuracy: 0.9809\n",
      "\n",
      "Epoch 00009: val_accuracy did not improve from 0.98980\n",
      "Epoch 10/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.6121 - accuracy: 0.7001 - val_loss: 0.0045 - val_accuracy: 0.9834\n",
      "\n",
      "Epoch 00010: val_accuracy did not improve from 0.98980\n",
      "Epoch 11/30\n",
      "114/114 [==============================] - 59s 520ms/step - loss: 1.0240 - accuracy: 0.6382 - val_loss: 0.3263 - val_accuracy: 0.9439\n",
      "\n",
      "Epoch 00011: val_accuracy did not improve from 0.98980\n",
      "Epoch 12/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.6946 - accuracy: 0.6475 - val_loss: 0.1874 - val_accuracy: 0.7908\n",
      "\n",
      "Epoch 00012: val_accuracy did not improve from 0.98980\n",
      "Epoch 13/30\n",
      "114/114 [==============================] - 61s 531ms/step - loss: 0.7119 - accuracy: 0.5806 - val_loss: 0.3147 - val_accuracy: 0.6594\n",
      "\n",
      "Epoch 00013: val_accuracy did not improve from 0.98980\n",
      "Epoch 14/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.7754 - accuracy: 0.5817 - val_loss: 4.3750e-08 - val_accuracy: 0.8214\n",
      "\n",
      "Epoch 00014: val_accuracy did not improve from 0.98980\n",
      "Epoch 15/30\n",
      "114/114 [==============================] - 57s 502ms/step - loss: 0.5027 - accuracy: 0.8021 - val_loss: 0.1094 - val_accuracy: 0.9617\n",
      "\n",
      "Epoch 00015: val_accuracy did not improve from 0.98980\n",
      "Epoch 16/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.4554 - accuracy: 0.6875 - val_loss: 0.5621 - val_accuracy: 0.4809\n",
      "\n",
      "Epoch 00016: val_accuracy did not improve from 0.98980\n",
      "Epoch 17/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 1.0023 - accuracy: 0.5910 - val_loss: 0.4997 - val_accuracy: 0.4847\n",
      "\n",
      "Epoch 00017: val_accuracy did not improve from 0.98980\n",
      "Epoch 18/30\n",
      "114/114 [==============================] - 59s 514ms/step - loss: 1.4399 - accuracy: 0.6354 - val_loss: 0.0625 - val_accuracy: 0.9668\n",
      "\n",
      "Epoch 00018: val_accuracy did not improve from 0.98980\n",
      "Epoch 19/30\n",
      "114/114 [==============================] - 60s 525ms/step - loss: 0.4043 - accuracy: 0.7407 - val_loss: 5.6250e-08 - val_accuracy: 0.9783\n",
      "\n",
      "Epoch 00019: val_accuracy did not improve from 0.98980\n",
      "Epoch 20/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 0.9969 - accuracy: 0.6009 - val_loss: 0.4839 - val_accuracy: 0.5676\n",
      "\n",
      "Epoch 00020: val_accuracy did not improve from 0.98980\n",
      "Epoch 21/30\n",
      "114/114 [==============================] - 57s 503ms/step - loss: 2.1358 - accuracy: 0.5367 - val_loss: 0.4875 - val_accuracy: 0.6173\n",
      "\n",
      "Epoch 00021: val_accuracy did not improve from 0.98980\n",
      "Epoch 22/30\n",
      "114/114 [==============================] - 58s 510ms/step - loss: 0.9968 - accuracy: 0.6848 - val_loss: 0.1249 - val_accuracy: 0.9286\n",
      "\n",
      "Epoch 00022: val_accuracy did not improve from 0.98980\n",
      "Epoch 23/30\n",
      "114/114 [==============================] - 58s 511ms/step - loss: 0.8492 - accuracy: 0.6809 - val_loss: 0.1874 - val_accuracy: 0.8214\n",
      "\n",
      "Epoch 00023: val_accuracy did not improve from 0.98980\n",
      "Epoch 24/30\n",
      "114/114 [==============================] - 63s 553ms/step - loss: 3.5376 - accuracy: 0.5088 - val_loss: 0.6246 - val_accuracy: 0.4809\n",
      "\n",
      "Epoch 00024: val_accuracy did not improve from 0.98980\n",
      "Epoch 25/30\n",
      "114/114 [==============================] - 61s 538ms/step - loss: 0.9672 - accuracy: 0.6360 - val_loss: 7.5000e-08 - val_accuracy: 0.9579\n",
      "\n",
      "Epoch 00025: val_accuracy did not improve from 0.98980\n",
      "Epoch 26/30\n",
      "114/114 [==============================] - 61s 538ms/step - loss: 0.5055 - accuracy: 0.8640 - val_loss: 3.7500e-08 - val_accuracy: 0.9923\n",
      "\n",
      "Epoch 00026: val_accuracy improved from 0.98980 to 0.99235, saving model to ./best_weights_for_Network.hdf5\n",
      "Epoch 27/30\n",
      "114/114 [==============================] - 61s 538ms/step - loss: 0.5353 - accuracy: 0.9079 - val_loss: 0.6246 - val_accuracy: 0.4974\n",
      "\n",
      "Epoch 00027: val_accuracy did not improve from 0.99235\n",
      "Epoch 28/30\n",
      "114/114 [==============================] - 63s 555ms/step - loss: 0.8538 - accuracy: 0.6826 - val_loss: 0.0625 - val_accuracy: 0.9885\n",
      "\n",
      "Epoch 00028: val_accuracy did not improve from 0.99235\n",
      "Epoch 29/30\n",
      "114/114 [==============================] - 65s 568ms/step - loss: 0.6459 - accuracy: 0.8728 - val_loss: 5.0000e-08 - val_accuracy: 0.9911\n",
      "\n",
      "Epoch 00029: val_accuracy did not improve from 0.99235\n",
      "Epoch 30/30\n",
      "114/114 [==============================] - 64s 564ms/step - loss: 0.6951 - accuracy: 0.8596 - val_loss: 5.6250e-08 - val_accuracy: 0.9031\n",
      "\n",
      "Epoch 00030: val_accuracy did not improve from 0.99235\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<keras.callbacks.callbacks.History at 0x2006f22a208>"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from keras.callbacks import ModelCheckpoint\n",
    "params={\n",
    "    'dim': (155,220),\n",
    "    'batch_size': 16,\n",
    "    'n_channels': 3,\n",
    "    'shuffle': False\n",
    "}\n",
    "\n",
    "#train_set = 2592*0.7 = 1814 == 1814/32 == 56\n",
    "#val_set = 2592*0.3 = 777 == 777/32 == 24\n",
    "ds_train = get_dataset(\"train\")\n",
    "ds_val = get_dataset(\"val\")\n",
    "train_datagen = DataGenerator(ds_train,**params)\n",
    "validation_datagen = DataGenerator(ds_val,**params)\n",
    "checkpointer = ModelCheckpoint(filepath=\"./best_weights_for_Network.hdf5\", \n",
    "                               monitor = 'val_accuracy',\n",
    "                               verbose=1, \n",
    "                               save_best_only=True)\n",
    "model.fit_generator(generator=train_datagen, validation_data=validation_datagen, epochs=30, steps_per_epoch=114, validation_steps=49,callbacks=[checkpointer])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "yoXaSfoBvJxr"
   },
   "outputs": [],
   "source": [
    "model.save(\"./colab_08072019.h5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "FOPbB5jyrklA"
   },
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([['./CEDAR/signatures/full_org\\\\original_18_17.png',\n        './CEDAR/signatures/full_forg\\\\forgeries_18_17.png', 0],\n       ['./CEDAR/signatures/full_org\\\\original_5_14.png',\n        './CEDAR/...",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-10-d63c83ad0b2a>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0mds_val\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mget_dataset\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"val\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[0mmod\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mload_model\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'./colab_08072019.h5'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mcustom_objects\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m{\u001b[0m\u001b[1;34m'contrastive_loss'\u001b[0m\u001b[1;33m:\u001b[0m\u001b[0mcontrastive_loss\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 6\u001b[1;33m \u001b[0my_prob\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mmod\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mds_val\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mc:\\users\\rakshit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\keras\\engine\\training.py\u001b[0m in \u001b[0;36mpredict\u001b[1;34m(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)\u001b[0m\n\u001b[0;32m   1439\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1440\u001b[0m         \u001b[1;31m# Case 2: Symbolic tensors or Numpy array-like.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1441\u001b[1;33m         \u001b[0mx\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0m_\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0m_\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_standardize_user_data\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1442\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstateful\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1443\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mx\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m>\u001b[0m \u001b[0mbatch_size\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0mx\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m%\u001b[0m \u001b[0mbatch_size\u001b[0m \u001b[1;33m!=\u001b[0m \u001b[1;36m0\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\rakshit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\keras\\engine\\training.py\u001b[0m in \u001b[0;36m_standardize_user_data\u001b[1;34m(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)\u001b[0m\n\u001b[0;32m    577\u001b[0m             \u001b[0mfeed_input_shapes\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    578\u001b[0m             \u001b[0mcheck_batch_axis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m  \u001b[1;31m# Don't enforce the batch size.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 579\u001b[1;33m             exception_prefix='input')\n\u001b[0m\u001b[0;32m    580\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    581\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\rakshit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\keras\\engine\\training_utils.py\u001b[0m in \u001b[0;36mstandardize_input_data\u001b[1;34m(data, names, shapes, check_batch_axis, exception_prefix)\u001b[0m\n\u001b[0;32m    107\u001b[0m                 \u001b[1;34m'Expected to see '\u001b[0m \u001b[1;33m+\u001b[0m \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnames\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;34m' array(s), '\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    108\u001b[0m                 \u001b[1;34m'but instead got the following list of '\u001b[0m \u001b[1;33m+\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 109\u001b[1;33m                 str(len(data)) + ' arrays: ' + str(data)[:200] + '...')\n\u001b[0m\u001b[0;32m    110\u001b[0m         \u001b[1;32melif\u001b[0m \u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mnames\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m>\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    111\u001b[0m             raise ValueError(\n",
      "\u001b[1;31mValueError\u001b[0m: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([['./CEDAR/signatures/full_org\\\\original_18_17.png',\n        './CEDAR/signatures/full_forg\\\\forgeries_18_17.png', 0],\n       ['./CEDAR/signatures/full_org\\\\original_5_14.png',\n        './CEDAR/..."
     ]
    }
   ],
   "source": [
    "from keras.models import load_model\n",
    "mod = load_model('./colab_08072019.h5',custom_objects={'contrastive_loss':contrastive_loss})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "`y` argument is not supported when data isa generator or Sequence instance. Instead pass targets as the second element of the generator.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-19-9c9960514a8c>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mloss\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maccuracy\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mf1_score\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mprecision\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrecall\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmod\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mevaluate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mvalidation_datagen\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_prob\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mverbose\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32mc:\\users\\rakshit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\keras\\engine\\training.py\u001b[0m in \u001b[0;36mevaluate\u001b[1;34m(self, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing)\u001b[0m\n\u001b[0;32m   1328\u001b[0m         \u001b[1;31m# Case 1: generator-like. Input is Python generator, or Sequence object.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1329\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mtraining_utils\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mis_generator_or_sequence\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1330\u001b[1;33m             \u001b[0mtraining_utils\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcheck_generator_arguments\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0msample_weight\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1331\u001b[0m             return self.evaluate_generator(\n\u001b[0;32m   1332\u001b[0m                 \u001b[0mx\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\rakshit\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\keras\\engine\\training_utils.py\u001b[0m in \u001b[0;36mcheck_generator_arguments\u001b[1;34m(y, sample_weight, validation_split)\u001b[0m\n\u001b[0;32m    317\u001b[0m     \u001b[1;34m\"\"\"Validates arguments passed when using a generator.\"\"\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    318\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 319\u001b[1;33m         raise ValueError('`y` argument is not supported when data is'\n\u001b[0m\u001b[0;32m    320\u001b[0m                          \u001b[1;34m'a generator or Sequence instance. Instead pass targets'\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    321\u001b[0m                          ' as the second element of the generator.')\n",
      "\u001b[1;31mValueError\u001b[0m: `y` argument is not supported when data isa generator or Sequence instance. Instead pass targets as the second element of the generator."
     ]
    }
   ],
   "source": [
    "loss, accuracy, f1_score, precision, recall = mod.evaluate(ds_val, y_prob, verbose=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "collapsed_sections": [],
   "name": "signet_keras.ipynb",
   "provenance": [],
   "version": "0.3.2"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
